### PR TITLE
fixed two different measurement result

### PR DESCRIPTION
**Pull request by Young799**
Thanks for the feedback :-) . Code updated to avoid getting to different measurement results.

### CODE REVIEW

**Review by platisd — CHANGES_REQUESTED** [review]
This looks fine, however someone cloning your repository would not be able to run this sketch unless they would place it in a directory with the same name, i.e. `sensor`.

To make things worse, this sketch is not being built on CI which should be unacceptable for any modern software engineer who knows what they are doing and wants to avoid problems.

Finally, I suspect you avoid using `git`. The earlier you start doing so, the better, so please do so asap.

**Comment by jousifkdawood** [comment]
> This looks fine, however someone cloning your repository would not be able to run this sketch unless they would place it in a directory with the same name, i.e. `sensor`.
> 
> To make things worse, this sketch is not being built on CI which should be unacceptable for any modern software engineer who knows what they are doing and wants to avoid problems.
> 
> Finally, I suspect you avoid using `git`. The earlier you start doing so, the better, so please do so asap.

The directory part, is it in the same sense as "absolute" and "relative path" ? , or am I misunderstanding. Also what do you mean by CI?

**Comment by platisd** [comment]
> > This looks fine, however someone cloning your repository would not be able to run this sketch unless they would place it in a directory with the same name, i.e. `sensor`.
> > To make things worse, this sketch is not being built on CI which should be unacceptable for any modern software engineer who knows what they are doing and wants to avoid problems.
> > Finally, I suspect you avoid using `git`. The earlier you start doing so, the better, so please do so asap.
> 
> The directory part, is it in the same sense as "absolute" and "relative path" ? , or am I misunderstanding. Also what do you mean by CI?

Arduino sketches have to be in a folder with the same name, otherwise they will not compile.
CI stands for Continuous Integration.

**Comment by JinaDawood** [comment]
> > > This looks fine, however someone cloning your repository would not be able to run this sketch unless they would place it in a directory with the same name, i.e. `sensor`.
> > > To make things worse, this sketch is not being built on CI which should be unacceptable for any modern software engineer who knows what they are doing and wants to avoid problems.
> > > Finally, I suspect you avoid using `git`. The earlier you start doing so, the better, so please do so asap.
> > 
> > 
> > The directory part, is it in the same sense as "absolute" and "relative path" ? , or am I misunderstanding. Also what do you mean by CI?
> 
> Arduino sketches have to be in a folder with the same name, otherwise they will not compile.
> CI stands for Continuous Integration.



> > > This looks fine, however someone cloning your repository would not be able to run this sketch unless they would place it in a directory with the same name, i.e. `sensor`.
> > > To make things worse, this sketch is not being built on CI which should be unacceptable for any modern software engineer who knows what they are doing and wants to avoid problems.
> > > Finally, I suspect you avoid using `git`. The earlier you start doing so, the better, so please do so asap.
> > 
> > 
> > The directory part, is it in the same sense as "absolute" and "relative path" ? , or am I misunderstanding. Also what do you mean by CI?
> 
> Arduino sketches have to be in a folder with the same name, otherwise they will not compile.
> CI stands for Continuous Integration.

Im sorry but I think we're kinda lost regarding CI, and everything we're supposed to download etc. I tried to follow the instructions in the workflow file (without knowing exactly what everything is for or what im doing). But I got stuck on the last thing. 
image

**Comment by platisd** [comment]
OK let me give some more hints because you are stranding of towards the wrong direction:
1. Sketches need to be placed in a directory with the same name. So if you have a `foo.ino` then it should be inside a directory called `foo`. So the sketch path would be something like `foo/foo.ino`.
2. The workflow file that you already have in the repository makes sure that the sketch found in `arduino/smartcar/smartcar.ino` is being built every time you push. This allows you to ensure that you have not introduced any breaking changes to the sketch. If you want to introduce new functionality you have the following options:
  1. Use the existing `smartcar/smartcar.ino` file as the place where your software resides. It will be automatically picked up by the existing CI configuration.
  2. If you want to use a different file, feel free to do so, but you should remove the one you are not using (i.e. the `smartcar.ino`) **and** you should make sure that the CI configuration is updated. You do not necessarily have to run the steps on your machine. I see you are on Windows so they aren't going to run without changes anyway.
 If you go for a different file, what you still have to do is change the path of the script that is being compiled on CI (currently the `smartcar.ino`) to the new one you may be using, whatever its new name and path may be.

**Comment by platisd** [comment]
The file is still not in the correct place to pick it up or in a correctly named directory but I will let you work on it.
Click on the "re-request review" button next to my nickname for me to have another look at it when you are ready.

**Comment by JinaDawood** [comment]
code snippet has been added to another file

**Pull request closed without merging**
