### PR TITLE
trying to solve CI problem related to MQTT library

### PR DESCRIPTION
**Pull request by JinaDawood**
*implemented MQTT connection in arduino
* closed pull request #36 and pushed to MQTT to another branch 

Co-Authored-By: Young799 81288695+Young799@users.noreply.github.com

### CODE REVIEW

**Review by platisd — COMMENTED** [review]
How are you supposed to be controlling the car? MQTT or serial?
Right now it's both and in an inconsistent manner.

**Comment by JinaDawood** [comment]
I know its inconsistent, but this is as far as we've come with MQTT and thats why the serial code is still there.

**Comment by JinaDawood** [comment]
> How are you supposed to be controlling the car? MQTT or serial?
> Right now it's both and in an inconsistent manner.

I know its inconsistent, but this is as far as we've come with MQTT and thats why the serial code is still there. We're going to continue tomorrow and trying to remove the serial

**Comment by platisd** [comment]
> > How are you supposed to be controlling the car? MQTT or serial?
> > Right now it's both and in an inconsistent manner.
> 
> I know its inconsistent, but this is as far as we've come with MQTT and thats why the serial code is still there. We're going to continue tomorrow and trying to remove the serial

OK if you're on it then I guess it looks good to me. No need to wait for my review, feel free to merge it.

**Review by gusandalce — APPROVED** [review]
looks good with the MQTT, we need to continue to add so we can remove the serial inputs

**Pull request merged**
