### PR TITLE
UI bug fix, enabling to display front sensor data

### LINKED ISSUE #67: Ultrasound front distance not showing on UI screen
The ultrasound front distance should appear on the manual page, but it's not.

### PR DESCRIPTION
**Pull request by JinaDawood**
Fixed problem related to #67. Front sensor data was previously not being displayed on the screen, which is now fixed. The ultrasound sensor data is now being used to warn the user when there is an obstacle that has been detected. When the vehicle is nearing an obstacle a warning shows on the screen. The code still needs some refinement, which will be tackled the upcoming sprint. 

Other small adjustments where also made to the layout of the manual screen and joystick implementation.

closes #67

### CODE REVIEW

**Comment by gusandalce** [comment]
i tried to run this after latest pull but got a compile error i'll look int o that to see if its something witht he code you changed or something on my end causing it

**Comment by JinaDawood** [comment]
> i tried to run this after latest pull but got a compile error i'll look int o that to see if its something witht he code you changed or something on my end causing it

try changing line 106 in arduino to: mqtt.onMessage([](String topic, String message)

**Comment by Young799** [comment]
> i tried to run this after latest pull but got a compile error i'll look int o that to see if its something witht he code you changed or something on my end causing it

I got the same problem with new MQTT line 106

**Review by gusandalce — APPROVED** [review]
tested with newer version of SMCE and seems to have fixed the bugs

**Pull request merged**
