### PR TITLE
Add methods to turn automatically if there is obstacle and integrate …

### LINKED ISSUE #29: Integrate more sensors
**Description**
As a Cleaning supervisor I want to be able to use several sensors so that the car will be more precise while driving

**Acceptance Criteria**
The vehicle will have 2 more sensors implemented into the system.

### LINKED ISSUE #32: Car turning left or right depending on obstacle
**Description**
As a Cleaning Supervisor I want the vehicle to automatically avoid and move around an object so that it won't crash and be damaged.

**Acceptance criteria**
The vehicle will turn 90 degrees left if an obstacle is in front and it has an obstacle on its right side.
The vehicle will turn 90 degrees right if an obstacle is in front and it has an obstacle on its left side.

### PR DESCRIPTION
**Pull request by Mozand**
…infrared sensors
Add infrared sensors to make the car able to turn autonomous based on the position of obstacles and choose the free path to continue.

closes #32 
closes #29

### CODE REVIEW

**Comment by Young799** [comment]
Iine 219, 222 need to be placed before 212 otherwise they will never execute since the first condition will always be met first.

**Review by Young799 — CHANGES_REQUESTED** [review]
Line 219, 222 need to be placed before 212 otherwise they will never execute since the first condition will always be met first.

**Review by JinaDawood — CHANGES_REQUESTED** [review]
We could replace line 168: 
instead of car.setSpeed(message.toInt());

we could go with: 
 currentSpeed = message.toInt();
       car.setSpeed(currentSpeed);

so that we set the currentSpeed that comes from the mqtt

**Review by JinaDawood — APPROVED** [review]
Looks good now! I've tested it and it works fine. We'll just have to fix the detection a bit better when it comes to trees next sprint

**Review by Young799 — APPROVED** [review]
Yes. The car turns automatically now.

**Pull request merged**
