### PR TITLE
CI for android app

### LINKED ISSUE #33: CI workflow for app
Add GitHub workflows (CI) for building android app.

### PR DESCRIPTION
**Pull request by JinaDawood**
Set up an Android CI through github actions,  which will build the android app every push and pull request.
 
Closed #33

### CODE REVIEW

**Comment by JinaDawood** [comment]
Does this look okay? or do I have to add more/change it?

**Review by platisd — COMMENTED** [review]
Indentation matters, everything line 10 is indented one more time than it should

**Comment by JinaDawood** [comment]
> Indentation matters, everything line 10 is indented one more time than it should

Do you mean that I should look over the indentation for the whole file or just line 10?

**Comment by platisd** [comment]
> > Indentation matters, everything line 10 is indented one more time than it should
> 
> Do you mean that I should look over the indentation for the whole file or just line 10?

Sorry, I mistyped. Everything **under** line 10.

**Comment by JinaDawood** [comment]
> > > Indentation matters, everything line 10 is indented one more time than it should
> > 
> > 
> > Do you mean that I should look over the indentation for the whole file or just line 10?
> 
> Sorry, I mistyped. Everything **under** line 10.

Changed it. Do we have to add more to it or is this good enough?

**Pull request merged**
