### PR TITLE
Auto mode UI_ Showing distance to UI

### PR DESCRIPTION
**Pull request by Young799**
Established a mqtt connection from arduino to android app. Its now possible to view the distance meaured by the odometer in the app. 

Closed issue #52

### CODE REVIEW

**Comment by JinaDawood** [comment]
> I just ran the code, but the distance is not showing. Maybe the textview is hiding behind something else.

It looks like its not constrained.

**Comment by Young799** [comment]
> > I just ran the code, but the distance is not showing. Maybe the textview is hiding behind something else.
> 
> It looks like its not constrained.

**Review by JinaDawood — APPROVED** [review]
I've tested the code during implementation and after being pushed and everything looks fine. We still have to do something about the distance layout. But the connection is smooth.

**Review by platisd — CHANGES_REQUESTED** [review]
You shouldn't be committing all these files!

**Comment by Young799** [comment]
I will closed this request and push the only code file again.

**Pull request closed without merging**
